fitnessapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from workouts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.workout_list, name="workouts"),
    path('workouts/<int:workout_id>/', views.workout_details, name='workout_details'),
    path('workouts/<int:workout_day_id>/<int:workout_id>/', views.workout_exercises, name='workout_exercises'),
    path('administrator/goals/', views.goal_list, name='admin_goals'),
    path('administrator/disabilities/', views.disability_list, name='admin_disabilities'),
    path('administrator/exercises/', views.exercise_list, name='admin_exercises'),
    path('administrator/workouts/', views.workoutadmin_list, name='admin_workouts'),
    path('administrator/workouts/<int:workout_id>/', views.workoutplan_list, name='workout-days'),
     path('calories', views.calories_intake, name='calories_intake'),


]

   
from django.contrib.auth import views as auth_views
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.sign_up, name='register'),
  
    path('profile/<str:username>/', views.profile_view, name='profile_view'),
    path('profile/edit/<str:username>/', views.change_profile, name='change_profile'),
    path('profile/<str:username>/posts/', views.user_posts, name='user_posts'),
    path('profile/<str:username>/reaction_post/<int:post_id>/', views.reaction_post, name='reaction_post'),
    path('profile/<str:username>/posts/new_post/', views.create_post, name='create_post'),
    path('profile/<str:username>/posts/following_posts/', views.followings_posts, name='followings_posts'),
    path('profile/posts/<int:post_id>/<str:username>/<str:view>/new_comment/', views.create_comment, name='create_comment'),
    path('search/', views.following_search, name='following-search'),
    path('profile/<str:username>/followers-unfollowers/', views.my_follows, name='my-follows'),
    path('profile/<str:username>/follow/', views.follow_view, name='follow'),
    path('profile/<str:username>/unfollow/', views.unfollow_view, name='unfollow'),
    path('profile/search-follow', views.following_search, name='following_search'),
    path('add_progress/<int:workout_day_id>//<int:workout_id>/', views.add_progress, name='add_progress'),
    path('profile/<str:username>/progress/', views.progress_list, name='progress_list'),
    path('progress/?filter=date_desc', views.progress_list, name='progress_list'),
    path('payment/', views.payment_view, name='payment'),
    path('payment_successful/', views.payment_successful_view, name='payment_successful'),
    path('contact/', views.contact_form, name='contact'),
    path('settings/', views.settings, name='settings'),
]

workouts/models/calories.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


class FoodCalories(models.Model):
    MEAL_CHOICES = [
        ('Mic Dejun', 'Mic Dejun'),
        ('Gustare', 'Gustare'),
        ('Pranz', 'Pranz'),
        ('Cina', 'Cina'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    meal_type = models.CharField(max_length=20, choices=MEAL_CHOICES)
    food = models.CharField(max_length=100)
    calories = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.user} - {self.date}, calories {self.calories}'

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

workouts/models/comment.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .post import Post

class Comment(models.Model):
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Comment by {self.user.username} on post {self.post.id}'

    def get_absolute_url(self):
        return reverse('post-detail', args=[str(self.post.id)])

workouts/models/disability.py
from django.db import models
from django.urls import reverse


class Disability(models.Model):
    name = models.CharField(max_length=200, help_text='Dati numele dizabilitatii')

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return self.name

workouts/models/exercise.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse



class Exercise(models.Model):
    name = models.CharField(max_length=20, help_text='Dati numele exercitiului')
    description = models.TextField()

    muscle_group = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return self.name

workouts/models/followers.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('follower', 'following')

    def __str__(self):
        return f"{self.follower.username} follows {self.following.username}"

workouts/models/friendship.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class Friendship(models.Model):
    id = models.AutoField(primary_key=True)
    user_1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_1")
    user_2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_2")

    def clean(self):
        if self.user1 == self.user2:
            raise ValidationError("User 1 and User 2 cannot be the same.")
        
    class Meta:
            ordering = ['user_1']

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return f"{self.user_1.username}'s friendship with {self.user_2.username} "
    @classmethod
    def send_friend_request(cls, sender_username, receiver_username):
        sender = User.objects.get(username=sender_username)
        receiver = User.objects.get(username=receiver_username)
        
        
        if cls.objects.filter(Q(user_1=sender, user_2=receiver) | Q(user_1=receiver, user_2=sender)).exists():
            return False  
        
        
        Friendship.objects.create(user_1=sender, user_2=receiver)
        return True

workouts/models/goal.py
from django.db import models
from django.urls import reverse


class Goal(models.Model):
    goal_name = models.CharField(max_length=20, help_text='Dati numele scopului antrenamentului')

    class Meta:
        ordering = ['goal_name']

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return self.goal_name

workouts/models/post.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
def image_path(instance, filename):  
    return "users/" + instance.user.username + "/posts/" + str(instance.id) +"." + filename.partition(".")[2]

class Post(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length=20, help_text='Titlul postarii')
    picture = models.ImageField(upload_to=image_path, blank=True, null=True)
    text = models.TextField(blank=True,null=True)
    time = models.DateTimeField(auto_now_add=True)
    post_choices = (
        ("Schimbare in greutate", "Schimbare in greutate"),
        ("Alt tip de postare", "Alt tip de postare"),
    )
    post_type = models.CharField(max_length=30, choices=post_choices, default="Alt tip de postare")

    class Meta:
            ordering = ['user']

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return f"{self.user.username}'s Post: {self.title}"

workouts/models/progress.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .workout_day import WorkoutDay

class Progress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    workout_day = models.ForeignKey(WorkoutDay, on_delete=models.CASCADE)
    class Meta:
            ordering = ['user']

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])
    
    def get_workout_name(self):
        return self.workout_day.workout.name

    def __str__(self):
        return f"{self.user.username}'s progress on {self.workout_day.day} "

workouts/models/reaction.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .post import Post

class Reaction(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="reactions")
    time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reactions")

    class Meta:
            ordering = ['post']

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return f"{self.user.username}'s reaction on {self.post.title} "

workouts/models/user_info.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


def image_path(instance, filename):
   
    return "users/" + instance.user.username + "/profile/" + "profile"+"." + filename.partition(".")[2]

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to=image_path, blank=True, null=True)
    
    date_of_birth = models.DateField(null=True, blank=True)
    current_weight = models.FloatField(null=True, blank=True)
    id = models.AutoField(primary_key=True)
    
    class Meta:
        ordering = ['user']

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return f'{self.user.username}\'s Profile'
    def save(self, *args, **kwargs):
        try:
            this = UserInfo.objects.get(id=self.id)
            if this.profile_image != self.profile_image:
                this.profile_image.delete(save=False)
        except UserInfo.DoesNotExist:
            pass

        super(UserInfo, self).save(*args, **kwargs)

workouts/models/user_payment.py
from django.db import models
from django.contrib.auth.models import User

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Payment #{self.id}"

workouts/models/workout.py
import re

from django.utils.translation import gettext_lazy as _

from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from .disability import Disability
from .goal import Goal


def validate_length(value):
    if value <= 0:
        raise ValidationError(
            _('%(value)s is not an even number'),
            params={'value': value},
        )


def image_path(instance, filename):
    
    return "workouts/" + instance.name + "." + filename.partition(".")[2]

class Workout(models.Model):
    name = models.CharField(max_length=20, help_text='Denumiti antrenamentul')
    disability = models.ForeignKey(Disability, on_delete=models.CASCADE, null=True, blank=True)
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE, null=True, blank=True)
    equipment_choices = (
        ("Nu, antrenament acasa", "Nu, antrenament acasa"),
        ("Da, antrenament la sala", "Da, antrenament la sala"),
    )
    equipment = models.CharField(max_length=25, choices=equipment_choices, default="Nu, antrenament acasa")
    level_choices = (
        ("Incepator", "Incepator"),
        ("Mediu", "Mediu"),
        ("Avansat", "Avansat"),
    )
    level = models.CharField(max_length=20, choices=level_choices, default="Incepator")
    length = models.IntegerField(validators=[validate_length], help_text="Numarul de zile")
    description = models.TextField()
    image = models.ImageField(upload_to=image_path, blank=True, null=True)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return self.name
    def save(self, *args, **kwargs):
        try:
            this = Workout.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete(save=False)
        except Workout.DoesNotExist:
            pass

        super(Workout, self).save(*args, **kwargs)

workouts/models/workout_day.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from .workout import Workout


def validate_day(value):
    if value <= 0:
        raise ValidationError(
            _('%(value)s is not an even number'),
            params={'value': value},
        )


class WorkoutDay(models.Model):
    day = models.IntegerField(validators=[validate_day], help_text="Numarul zilei")
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)

    class Meta:
        ordering = ['day']

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return str(self.day) + " " + self.workout.name;

workouts/models/workout_day_exercise.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from .workout_day import WorkoutDay
from django.utils.translation import gettext_lazy as _
from .exercise import Exercise


def validate(value):
    if value < 0:
        raise ValidationError(
            _('%(value)s is not an even number'),
            params={'value': value},
        )


class WorkoutDayExercise(models.Model):
    workout_day = models.ForeignKey(WorkoutDay, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    specification_choices = (
        ("Timp", "Timp"),
        ("Seturi si Repetitii", "Seturi si Repetitii"),
    )
    specification = models.CharField(max_length=20, choices=specification_choices,
                                     default="Seturi si Repetitii")
    time = models.IntegerField(validators=[validate], default=0)
    sets = models.IntegerField(validators=[validate], default=0)
    repetitions = models.IntegerField(validators=[validate], default=0)

    class Meta:
        ordering = ['workout_day']
        
    @property
    def workout_name(self):
        return self.workout_day.workout.name

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return self.exercise.name + " " + str(self.workout_day.day) + " " + self.workout_day.workout.name

workouts/forms/calories.py
from django import forms
from workouts.models import FoodCalories

class CaloriesForm(forms.ModelForm):
    class Meta:
        model = FoodCalories
        fields = ['meal_type', 'food', 'calories']

workouts/forms/contact.py
from django import forms

class ContactForm(forms.Form):
    username = forms.CharField(max_length=100, required=False)
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Adaugă mesajul...',
        })
        self.fields['text'].label = 'Adauga mesajul'
   

workouts/forms/follows.py
from django import forms
from workouts.models import Follow

class FollowForm(forms.ModelForm):
    class Meta:
        model = Follow
        fields = []

class UnfollowForm(forms.ModelForm):
    class Meta:
        model = Follow
        fields = []

workouts/forms/new_comment.py
from django import forms
from workouts.models import Comment

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('text', 'parent_comment',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Adaugă un comentariu...',
        })

workouts/forms/new_post.py
from django import forms
from workouts.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'picture', 'text', 'post_type']

templates/admin_templates/workout_plan.html
{% extends 'base_generic.html' %}
{% block content %}
<style>
  #id_repetitions, #id_time, #id_sets{
    min-height: 50px;
    width: 100%;
    border: none;
    border-bottom: 1px solid #ccc;
    font-size: 16px;
    padding: 10px 0;
    box-sizing: border-box;
    height: 30px;
  }
</style>
<div class="main">
  <h1><a href="{% url 'workout_details' workout_id=workout.id %}">{{ workout.name }}</a> - Plan</h1>
  <ul>
    <div style="background-color: #f2f2f2;">
      {% for workout_day in workout_days %}
        <li>
          <button onclick="toggleDay({{ workout_day.day }})"
          style="background-color: black;
          color: white;
          padding: 14px 20px;
          margin: 8px 0;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          font-size: 15px; 
          padding: 2px 8px;
          "
          id="button-{{ workout_day.day }}"
          >Ascunde</button>
          <h2>Ziua {{ workout_day.day }}</h2>
          <ul id="day-{{ workout_day.day }}">
            {% for exercise in workout_day.workoutdayexercise_set.all %}
              <div style="border: 1px solid #ccc; padding: 5px; margin-bottom: 10px;">
                <div style="display: flex; align-items: center; ">
                  <li style="display: flex; align-items: center;"><b>Exercitiu: {{ exercise.exercise.name }}</b></li>
                  <form method="POST" action="" style="background-color: transparent; margin-left: 5px;">
                    {% csrf_token %}
                    {{ exercise_delete_form.as_p }}
                    <input type="hidden" name="workoutexercise_id" value="{{ exercise.id }}">
                    <button type="submit" name="delete-exercise" style="font-size: 15px; padding: 2px 8px;">Sterge</button>
                  </form>
                  <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>Specificatie: {{ exercise.specification }}</i></li>
                  <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>Timp(secunde): {{ exercise.time }}</i></li>
                  <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>Set: {{ exercise.sets }}</i></li>
                  <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>Repetitii: {{ exercise.repetitions }}</i></li>
                </div>
              </div>
            {% empty %}
              <li>Niciun exercitiu adaugat inca.</li>
            {% endfor %}
          </ul>
          <div style="height: 10px; background-color: white;"></div>
          <h3> Adauga exercitii pentru ziua {{ workout_day.day }}</h3>
          <form method="POST" action="{% url 'workout-days' workout.id %}">
            {% csrf_token %}
            <label for="{{ exercise_form.id_for_label }}">Exercitiu:</label>
            {{ exercise_form.exercise }}
            <label for="{{ exercise_form.id_for_label }}">Specificatie:</label>
            {{ exercise_form.specification}}
            
            <label for="id_time" style ="display:none;">Timp(secunde):</label>
            <input type="number" id="id_time" name="time" value="0" style ="display:none;">
            
            <label for="id_sets" style="display: block;">Seturi:</label>
            <input type="number" id="id_sets" name="sets" value="0" style="display: block;">
            <label for="id_repetitions" style="display: block;">Repetitii:</label>
            <input type="number" id="id_repetitions" name="repetitions" value="0" style="display: block;">



            <input type="hidden" name="workout_day_id" value="{{ workout_day.id }}">
            <button type="submit" name="add-exercise">Adauga exercitiu</button>
          </form>
          <div style="height: 10px; background-color: white;"></div>
        </li>
      {% empty %}
        <li>Nu exista zile.</li>
      {% endfor %}
    </div>
  </ul>
  
  {% if workout_days.has_other_pages %}
    <div class="pagination" style="text-align: center;">
      {% if workout_days.has_previous %}
        <a href="?page=1" style="color: #45a049">&laquo; Inceput</a>
        <a href="?page={{ page_obj.previous_page_number }}" style="color: #45a049">Anterior</a>
      {% endif %}
      
      {% for page in workout_days.paginator.page_range %}
        {% if page == workout_days.number %}
          <span class="current-page">{{ page }}</span>
        {% else %}
          <a style="color: #45a049" href="?page={{ page }}">{{ page }}</a>
        {% endif %}
      {% endfor %}
      
      {% if workout_days.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" style="color: #45a049">Urmator</a>
      <a href="?page={{ page_obj.paginator.num_pages }}" style="color: #45a049">Final &raquo;</a>
      {% endif %}
    </div>
  {% endif %}
</div>

<script>
  function toggleDay(day) {
    const dayElement = document.getElementById(`day-${day}`);
    const headingElement = dayElement.previousElementSibling;
    const buttonElement = document.getElementById(`button-${day}`);
    if (dayElement.style.display === 'none') {
      dayElement.style.display = 'block';
      headingElement.style.display = 'block';
      buttonElement.textContent = 'Ascunde';
    } else {
      dayElement.style.display = 'none';
      headingElement.style.display = 'none';
      buttonElement.textContent = 'Afiseaza';
    }


  }
   const specificationFields = document.querySelectorAll('select[name="specification"]');
   const timeLabels = document.querySelectorAll('label[for="id_time"]');
   const timeInputs = document.querySelectorAll('input[name="time"]');
   const setsLabels = document.querySelectorAll('label[for="id_sets"]');
   const setsInputs = document.querySelectorAll('input[name="sets"]');
   const repetitionsLabels = document.querySelectorAll('label[for="id_repetitions"]');
   const repetitionsInputs = document.querySelectorAll('input[name="repetitions"]');

   specificationFields.forEach((specificationField, index) => {
     specificationField.addEventListener('change', function() {
       if (specificationField.value === 'Timp') {
        
         timeLabels[index].style.display = 'block';
         timeInputs[index].style.display = 'block';
         setsLabels[index].style.display = 'none';
         setsInputs[index].style.display = 'none';
         repetitionsLabels[index].style.display = 'none';
         repetitionsInputs[index].style.display = 'none';
       
       } else {
         timeLabels[index].style.display = 'none';
         timeInputs[index].style.display = 'none';
         setsLabels[index].style.display = 'block';
         setsInputs[index].style.display = 'block';
         repetitionsLabels[index].style.display = 'block';
         repetitionsInputs[index].style.display = 'block';
      }
    });
  });
  


</script>
{% endblock %}

templates/admin_templates/workouts.html
{% extends 'base_generic.html' %}
{% block content %}
<style>
  #hideAllButton{
    background-color: black;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 15px; 
    padding: 2px 8px;
  }
  input[type="file"] {
    display: none;
  }
  .custom-file-upload {
    border: 1px solid #ccc;
    display: inline-block;
    padding: 6px 12px;
    cursor: pointer;
  }
  textarea {
    min-height: 50px;
    width: 100%;
    border: none;
    border-bottom: 1px solid #ccc;
    font-size: 16px;
    padding: 10px 0;
    box-sizing: border-box;
    height: 30px;
  }
  textarea:focus {
    
    outline: none;
  }
  #id_length{
    min-height: 50px;
    width: 100%;
    border: none;
    border-bottom: 1px solid #ccc;
    font-size: 16px;
    padding: 10px 0;
    box-sizing: border-box;
    height: 30px;
  }

</style>
<div class="main">
  
  <button id="hideAllButton">Ascunde toate antrenamentele</button>
  <h2>Lista de antrenamente</h2>
  <div id="workoutsList">
    <h3>Aplicati filtre</h3>
    <form action="" method="get">

      <label for="name">Nume:</label>
      <input type="text" name="name" id="name" value="{{ request.GET.name|default:'' }}">
      
  
      <button type="submit">Filtreaza</button>
    </form>
    <div style="height: 10px; background-color: white;"></div>
    {% for workout in workouts %}
    <div style="background-color: #eaeaea;">
      <div style="display: flex; align-items: center;">
        <span>Nume antrenament: <a href="{% url 'workout-days' workout.id %}">{{ workout.name }}</a></span>
        <form method="POST" action="" style="background-color: transparent; margin-left: 5px;">
          {% csrf_token %}
          {{ delete_form.as_p }}
          <input type="hidden" name="workout_id" value="{{ workout.id }}">
          <button type="submit" name="delete-goal" style="font-size: 15px; padding: 2px 8px;">Sterge</button>
        </form>
      </div>
      <div style="height: 10px; background-color: white;"></div>
    </div>
    {% endfor %}
  </div>

<h2>Adaugati un nou antrenament</h2>
<form method="POST" action="" enctype="multipart/form-data">
  {% csrf_token %}
  <label for="{{ form.name.id_for_label }}">Nume:</label>
  {{ form.name }}
  <label for="{{ form.disability.id_for_label }}">Dizabilitate:</label>
  {{ form.disability }}
  <label for="{{ form.goal.id_for_label }}">Obiectiv:</label>
  {{ form.goal }}
  <label for="{{ form.equipment.id_for_label }}">Echipament:</label>
  {{ form.equipment }}
  <label for="{{ form.level.id_for_label }}">Dificultate:</label>
  {{ form.level }}
 
  <label for="{{ form.description.id_for_label }}">Descriere:</label>
  {{ form.description }}</br>
  <label for="{{ form.length.id_for_label }}">Lungime(zile):</label>
  {{ form.length }}</br>
  <label for="{{ form.image.id_for_label }}">Imagine de profil:</label>
  <label for="{{ form.image.id_for_label }}" class="custom-file-upload">
    <i class="fa fa-cloud-upload"></i> Selecteaza Imaginea
  </label>
  {{ form.image }}

  
  <button type="submit"> Adauga antrenament </button>
</form>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    const hideAllButton = document.getElementById('hideAllButton');
    const workoutsList= document.getElementById('workoutsList');
    const descriptionField = document.querySelector('#{{ form.description.id_for_label }}');
    descriptionField.addEventListener('input', function() {
      this.style.height = 'auto';
      this.style.height = this.scrollHeight + 'px';
    });
    descriptionField.setAttribute('rows', '1');

    hideAllButton.addEventListener('click', function() {
      if (workoutsList.style.display === 'none') {
        workoutsList.style.display = 'block';
        hideAllButton.innerText = 'Ascunde toate antrenamentele';
      } else {
        workoutsList.style.display = 'none';
        hideAllButton.innerText = 'Afiseaza toate antrenamentele';
      }
    });
  });
</script>
{% endblock %}